DROP TABLE IF EXISTS saved_game_players;
DROP TABLE IF EXISTS saved_game_teams;
DROP TABLE IF EXISTS saved_games;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS locations;