DROP TABLE IF EXISTS GameParticipation;
DROP TABLE IF EXISTS Players;
DROP TABLE IF EXISTS SavedGames;
DROP TABLE IF EXISTS Teams;
DROP TABLE IF EXISTS Locations;
DROP EXTENSION IF EXISTS "uuid-ossp";