CREATE TABLE IF NOT EXISTS Locations(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    location_name VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS Teams(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    location_id UUID NOT NULL UNIQUE

    FOREIGN KEY (location_id) REFERENCES Locations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SavedGames(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    location_id UUID NOT NULL
    winner VARCHAR(60) NOT NULL
    total_score INT
    average_score DOUBLE PRECISION
    is_team_game BOOLEAN NOT NULL
 
    FOREIGN KEY (location_id) REFERENCES Locations(id) ON DELETE CASCADE
);